name: TSMNet
channels:
  - conda-forge
  - defaults
dependencies:
   # basic programs
   - python==3.12
   - pip
   # scientific python base packages
   - numpy
   - pandas
   - scipy
   # jupyter notebooks
   - ipykernel
   - notebook
   - jupyterlab
   - nb_conda_kernels
   # python visualization
   - matplotlib
   - seaborn
   # machine learning
   - scikit-learn
   - pytorch
   - torchvision
   - skorch
   - pip:
      # tensorboard
      - tensorboard
      # m/eeg analysis
      - mne
      - moabb
      # command line interfacing
      - hydra-core
      - hydra-joblib-launcher
      # machine learning
      - pyriemann
      - git+https://github.com/geoopt/geoopt.git
      # this package
      - -e .